### PR TITLE
Upgrade consolidate.js; add swig as dev-dependency.

### PR DESCRIPTION
**Pull request by jgerigmeyer**
- `consolidate.js` has added new features, especially related to using `nunjucks.js`
- `swig` is a requirement for running the tests locally.

### CODE REVIEW

**Comment by pascalduez** [comment]
:+1:  LGTM

Note: 
if you're up to build a SassDoc theme, you might be interested to know that Themeleon is no longer required. 
See:
https://github.com/themeleon/themeleon/blob/develop/README.md
https://github.com/SassDoc/sassdoc-theme-default/blob/master/src/index.js
https://github.com/pascalduez/sassdoc-theme-literate/blob/master/src/index.js

**Comment by jgerigmeyer** [comment]
Thanks! I took your advice and just wrote my own... :+1:

**Comment by valeriangalliat** [comment]
Cool, thank! And +1 to @pascalduez's comment.

**Comment by valeriangalliat** [comment]
Published in 3.0.2

**Pull request merged**
